### ISSUE TITLE
1983 error with sstv-0.0.8

### ISSUE THREAD

**Issue by WisdomLove** [jianchang512/stt#11]
2024-01-28 12:06:00.8464605 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1983 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.

Environment

windows 10 22H2

nvidia 551.23
cuda 12.3.2_546.12
cudnn-windows-x86_64-8.9.6.50_cuda12-archive

**Comment by WisdomLove** [comment]
MODIIED FRM CPU TO CUDA ALREADY.

**Comment by WisdomLove** [comment]
also with the issue with CPU

**Comment by jianchang512** [comment]
2024-01-28 12:06:00.8464605 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1983 
    onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.

This is just a warning, not an error, it does not affect the use

Because it was converted from OpenAI Whisper to Faster Whisper, there may be some regulatory issues in the environment, which does not affect its use

**Comment by WisdomLove** [comment]
Works well with CPU and  GPU now.
